name: 'Setup Java Development Kits built by Oracle'
description: 'Download and set up a JDK built by Oracle'

branding:
  icon: 'download-cloud'
  color: 'red'

inputs:
  website:
    description: 'Site to download JDK from: `oracle.com` or `jdk.java.net`'
    required: true
    default: 'oracle.com'
  release:
    description: 'Feature release number or project name, defaults to `24`'
    required: true
    default: '24'
  version:
    description: 'Additional version information, defaults to `latest`'
    required: true
    default: 'latest'
  install:
    description: 'Install the downloaded JDK archive file by running actions/setup-java, defaults to `true`'
    required: true
    default: 'true'
  install-as-version:
    description:
      Controls which value is passed as `java-version` to actions/setup-java, defaults to `PARSE_URI`
      if `release` starts with a digit, else it defaults to `HASH_URI`
    required: false
  uri:
    description: 'URI of JDK archive file to download'
    required: false

outputs:
  archive:
    description: 'The path to the downloaded JDK archive file'
    value: ${{ steps.download.outputs.archive }}
  version:
    description: 'The version of the downloaded JDK'
    value: ${{ steps.download.outputs.version }}

runs:
  using: 'composite'
  steps:
    - name: 'Download Java Development Kit'
      id: download
      shell: bash
      env:
        WEBSITE: "${{ inputs.website }}"
        RELEASE: "${{ inputs.release }}"
        VERSION: "${{ inputs.version }}"
        INSTALL_AS_VERSION: "${{ inputs.install-as-version }}"
        URI: "${{ inputs.uri }}"
      run: |
        echo "::group::Prepare download..."
        JAVA=$JAVA_HOME_21_X64/bin/java
        if [ ! -d "$JAVA_HOME_21_X64" ]; then
          JAVA=$JAVA_HOME_21_arm64/bin/java
        fi
        $JAVA --version
        DOWNLOAD=$GITHUB_ACTION_PATH/src/Download.java
        echo "::endgroup::"
        if [ ! -z "$URI" ]; then
          $JAVA \
            -Dinstall-as-version="$INSTALL_AS_VERSION" \
            "$DOWNLOAD" \
            "$URI"
        else
          $JAVA \
            -Dinstall-as-version="$INSTALL_AS_VERSION" \
            "$DOWNLOAD" \
            "$WEBSITE" \
            "$RELEASE" \
            "$VERSION"
        fi
    - name: 'Install Java Development Kit'
      if: ${{ inputs.install  == 'true' }}
      uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
      with:
        java-version: ${{ steps.download.outputs.version }}
        distribution: jdkfile
        jdkFile: ${{ steps.download.outputs.archive }}
