on:
  workflow_dispatch:
    inputs:
      name:
        description: 'List JDK uris at https://jdk.java.net/{NAME}/'
        required: false
        type: string

jobs:
  list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - run: $JAVA_HOME_21_X64/bin/java --show-version src/ListOpenJavaDevelopmentKits.java ${{ github.event.inputs.name }}
