on:
  workflow_call:
  workflow_dispatch:

jobs:
  latest:
    name: "Latest JDK ${{ matrix.release }} on ${{ matrix.os }}"
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: [ ubuntu-latest , macos-latest, windows-latest ]
        release: [ 17 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v4
      - name: 'Set up JDK'
        id: setup
        uses: ./
        with:
          website: oracle.com
          release: ${{ matrix.release }}
          version: latest
      - name: 'Print outputs'
        shell: bash
        run: |
          echo 'Outputs'
          echo "steps.setup.outputs.archive = ${{ steps.setup.outputs.archive }}"
          echo "steps.setup.outputs.version = ${{ steps.setup.outputs.version }}"
      - name: 'Print Java version'
        run: java --version
