name: Print Java Versions

on:
  workflow_dispatch:

jobs:
  print:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, macos-14, macos-13, macos-12, macos-11, windows-2022, windows-2019]
    name: "${{ matrix.os }} x ${{ matrix.jdk }}"
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'JAVA_HOME_8_*'
        shell: bash
        run: |
          echo "JAVA_HOME_8_X64    = $JAVA_HOME_8_X64"
          if [ -d "$JAVA_HOME_8_X64" ]; then
            $JAVA_HOME_8_X64/bin/java -version
          fi
          echo "JAVA_HOME_8_arm64  = $JAVA_HOME_8_arm64"
          if [ -d "$JAVA_HOME_8_arm64" ]; then
            $JAVA_HOME_8_arm64/bin/java -version
          fi
      - name: 'JAVA_HOME_11_*'
        shell: bash
        run: |
          echo "JAVA_HOME_11_X64    = $JAVA_HOME_11_X64"
          if [ -d "$JAVA_HOME_11_X64" ]; then
            $JAVA_HOME_11_X64/bin/java -version
          fi
          echo "JAVA_HOME_11_arm64  = $JAVA_HOME_11_arm64"
          if [ -d "$JAVA_HOME_11_arm64" ]; then
            $JAVA_HOME_11_arm64/bin/java -version
          fi
      - name: 'JAVA_HOME_17_*'
        shell: bash
        run: |
          echo "JAVA_HOME_17_X64    = $JAVA_HOME_17_X64"
          if [ -d "$JAVA_HOME_17_X64" ]; then
            $JAVA_HOME_17_X64/bin/java -version
          fi
          echo "JAVA_HOME_17_arm64  = $JAVA_HOME_17_arm64"
          if [ -d "$JAVA_HOME_17_arm64" ]; then
            $JAVA_HOME_17_arm64/bin/java -version
          fi
      - name: 'JAVA_HOME_21_*'
        shell: bash
        run: |
          echo "JAVA_HOME_21_X64    = $JAVA_HOME_21_X64"
          if [ -d "$JAVA_HOME_21_X64" ]; then
            $JAVA_HOME_21_X64/bin/java -version
          fi
          echo "JAVA_HOME_21_arm64  = $JAVA_HOME_21_arm64"
          if [ -d "$JAVA_HOME_21_arm64" ]; then
            $JAVA_HOME_21_arm64/bin/java -version
          fi
